### ISSUE TITLE
Seems to be ineffective.

### ISSUE THREAD

**Issue by Sanj1Ng** [dysphie/nmrih-weapon-configs-ex#3]
"weaponconfig"
{

	"me_kitknife"
	{
		"damage" "350"
	}
}

The game worked before the update, and now it doesn't seem to work，I only tested me_kitknife。

**Comment by dysphie** [comment]
Are you on version [1.1.13](https://github.com/dysphie/nmrih-weapon-configs-ex/releases/tag/1.1.13)?

**Comment by Sanj1Ng** [comment]
> Are you on version [1.1.13](https://github.com/dysphie/nmrih-weapon-configs-ex/releases/tag/1.1.13)?

yes,1.13.4 support (untested)

**Comment by Sanj1Ng** [comment]
https://github.com/dysphie/nmrih-weapon-configs-ex/releases/tag/1.1.13
I updated this version，All damage It all seems to have failed

**Comment by Sanj1Ng** [comment]
"me_kitknife"
	{
		"damage" "350"
	}
It worked fine in the last version until the game was updated

**Comment by dysphie** [comment]
I see, thanks. I will take a better look

**Comment by dysphie** [comment]
The issue should be resolved now in [1.1.14](https://github.com/dysphie/nmrih-weapon-configs-ex/releases/tag/1.1.14)

**Comment by Sanj1Ng** [comment]
thank you

**Comment by ymbpa5475** [comment]
![image](https://github.com/dysphie/nmrih-weapon-configs-ex/assets/147923906/02ec4f00-ce50-4388-abd3-a6d2e5ecf36c)

**Comment by dysphie** [comment]
> ![image](https://github.com/dysphie/nmrih-weapon-configs-ex/assets/147923906/02ec4f00-ce50-4388-abd3-a6d2e5ecf36c)
> 

Hi, try to avoid commenting on unrelated closed issues. Your error is caused by having an old version of DHooks. Simply upgrade Sourcemod to a newer version since it comes bundled with it.
