### ISSUE TITLE
Damage changes to melee weapons are static.

### ISSUE THREAD

**Issue by Addasu** [dysphie/nmrih-weapon-configs-ex#4]
Any changes that are made to melee damage don't take the charging mechanic into account. They're stuck at whatever value you change 'damage' and 'damage_headshot' to.

Would it be possible to implement another stat specifically for melee weapon damage so they can be altered dynamically?

**Comment by dysphie** [comment]
Hello, `damage` should now account for charge length in 1.2.0+

**Comment by Addasu** [comment]
Just tested. Works perfectly. Excellent job Dysphie, thanks!
