### ISSUE TITLE
Not working in NMRIH new version 1.13.5

### ISSUE THREAD

**Issue by h266579110** [dysphie/nmrih-weapon-configs-ex#6]
SourceMod (1.12.0.7137)

> L 05/29/2024 - 13:15:22: [SM] Exception reported: Failed to setup detour for CNMRiH_WeaponBase::AllowsSuicide
> L 05/29/2024 - 13:15:22: [SM] Blaming: weapon-configs.smx
> L 05/29/2024 - 13:15:22: [SM] Call stack trace:
> L 05/29/2024 - 13:15:22: [SM]   [0] SetFailState
> L 05/29/2024 - 13:15:22: [SM]   [1] Line 2251, weapon-configs.sp::RegDetour
> L 05/29/2024 - 13:15:22: [SM]   [2] Line 2226, weapon-configs.sp::LoadDetours
> L 05/29/2024 - 13:15:22: [SM]   [3] Line 295, weapon-configs.sp::OnPluginStart
> L 05/29/2024 - 13:15:22: [SM] Unable to load plugin "weapon-configs.smx": Error detected in plugin startup (see error logs)

**Comment by dysphie** [comment]
Thanks for the report, try [1.1.15](https://github.com/dysphie/nmrih-weapon-configs-ex/releases/tag/1.1.15)

**Comment by h266579110** [comment]
Now will crashing server when someone throwing molotov
in NMRIH new version 1.13.6

**Comment by dysphie** [comment]
Pushed a fix for the nade crash in  [1.2.0](https://github.com/dysphie/nmrih-weapon-configs-ex/releases/tag/1.2.0)
